# Site settings
title: Nautilus Desktop
email: yeahdongcn@gmail.com
url: https://yeahdongcn.github.io/
description: "The Missing vctl UI for macOS."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: github
    url: https://github.com/yeahdongcn

# Build settings
markdown: kramdown
permalink: pretty
